import { expect, test } from "@playwright/test";
import { shelfFixture } from "../fixtures/personal-shelf";
import { createOwnerToken, OWNER_COOKIE } from "../../src/server/shelf-owner";
test.skip(process.env.SHELF_RESEARCH_QUEUE_ENABLED !== "true" || !process.env.SHELF_OWNER_SECRET, "Owner test configuration required");
test("verified owner scans without billing or funnel events only on the pilot URL", async ({ page, context }) => {
  const token = createOwnerToken("link")!;
  await page.addInitScript(() => { localStorage.setItem("sugar_scanner_onboarding_v1", "completed"); localStorage.setItem("sugar_scanner_free_scans_v1", "3"); });
  const calls: string[] = [];
  page.on("request", r => { if (/\/api\/(events|billing\/)/.test(r.url())) calls.push(r.url()); });
  await page.goto(`/pilot/shelf/owner#token=${token}`);
  await page.getByRole("button", { name: "Enable my free access" }).click();
  await expect(page.getByText("Owner access · Free scans", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText("Owner access · Free scans", { exact: true })).toBeVisible();
  const product = shelfFixture("owner-qa-chips");
  const detection = { productId: product.id, catalogProductId: product.id, confidence: .99, box: { x: .1, y: .1, width: .6, height: .6 }, observedText: product.name, identity: { brand: product.brand, name: product.name, variant: null, packSize: "100g", category: "Chips", matchKind: "barbora" }, inlineProduct: product, shelfPrice: null, retailerOffer: null };
  let scans = 0;
  await page.route("**/api/recognize", route => { scans++; return route.fulfill({ json: { requestId: "owner-qa", status: "matched", latencyMs: 1, model: "fixture", imageStored: false, detections: [detection] } }); });
  await page.route("**/api/resolve-products", route => route.fulfill({ json: { detections: [detection], latencyMs: 1, imageStored: false } }));
  await page.route("**/api/pilot/shelf-queue", route => route.fulfill({ json: { items: [] } }));
  await page.route("**/api/personal-shelf", route => route.fulfill({ json: { evidence: {} } }));
  await page.getByRole("button", { name: "Show demo", exact: true }).click();
  await page.getByRole("dialog", { name: "See how it works" }).locator('input[type="file"]').setInputFiles({ name: "owner-qa.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64") });
  await expect.poll(() => scans).toBeGreaterThan(0);
  await expect(page.getByRole("dialog", { name: "Keep scanning shelves" })).toHaveCount(0);
  expect(calls).toEqual([]);
  expect(await page.evaluate(() => localStorage.getItem("sugar_scanner_free_scans_v1"))).toBe("3");
  expect((await context.cookies()).find(c => c.name === OWNER_COOKIE)?.path).toBe("/pilot/shelf");
  expect(await page.locator('link[rel="manifest"]').getAttribute("href")).toBe("/pilot/shelf/manifest.webmanifest");
  const manifest = await (await page.request.get("/pilot/shelf/manifest.webmanifest")).json(); expect(manifest.start_url).toBe("/pilot/shelf");
  await page.route("**/api/billing/status", route => route.fulfill({ json: { active: false } }));
  await page.goto("/");
  await expect(page.getByText("Owner access · Free scans", { exact: true })).toHaveCount(0);
  await expect.poll(() => calls.some(url => url.includes("/api/billing/status"))).toBe(true);
  await expect(page.getByRole("dialog", { name: "Keep scanning shelves" })).toBeVisible();
});
test("visitors and forged cookies retain the pilot paywall", async ({ page, context, baseURL }) => {
  await page.addInitScript(() => { localStorage.setItem("sugar_scanner_onboarding_v1", "completed"); localStorage.setItem("sugar_scanner_free_scans_v1", "3"); });
  await context.addCookies([{ name: OWNER_COOKIE, value: "forged", domain: new URL(baseURL!).hostname, path: "/pilot/shelf" }]);
  let checked = false; await page.route("**/api/billing/status", route => { checked = true; return route.fulfill({ json: { active: false } }); });
  await page.goto("/pilot/shelf");
  await expect.poll(() => checked).toBe(true);
  await expect(page.getByText("Owner access · Free scans", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("dialog", { name: "Keep scanning shelves" })).toBeVisible();
});
